name: CI/CD Pipeline

on:
  push:
    branches: ['main']
  pull_request:
    branches: ['main']
  workflow_dispatch:

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Node 16
        uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: 'yarn'

      - name: Install dependencies
        run: yarn run init:ci

      - name: Build Core
        run: yarn build:core

      - name: Build Client
        run: yarn build:client

      - name: Build Server
        run: yarn build:server

  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Node 16
        uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: 'yarn'

      - name: Install dependencies
        run: yarn run init:ci

      - name: Build Core
        run: yarn build:core

      - name: Lint Core
        run: yarn lint:core

      - name: Lint Client
        run: yarn lint:client

      - name: Lint Server
        run: yarn lint:server

  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Node 16
        uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: 'yarn'

      - name: Install dependencies
        run: yarn run init:ci

      - name: Build Core
        run: yarn build:core

      - name: Test Core
        run: yarn test:core

      - name: Test Client
        run: yarn test:client

      - name: Test Server
        run: yarn test:server

      - name: Upload coverage report
        uses: codecov/codecov-action@v3
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
